version: '3.8'

services:
  rabbitNode1:
    image: rabbitmq:3-management
    container_name: rabbitNode1
    hostname: node1.rabbit
    networks:
      cluster-network:
        ipv4_address: 192.168.0.10
    extra_hosts:
      - "node2.rabbit:192.168.0.11"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35672:35672"
    environment:
      - RABBITMQ_USE_LONGNAME=true
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_CLUSTERED=true
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@node1.rabbit
      - RABBITMQ_NODENAME=rabbit@node1.rabbit
      - RABBITMQ_DEFAULT_USER=maxibanex
      - RABBITMQ_DEFAULT_PASS=maxibanexRG20.

  rabbitNode2:
    image: rabbitmq:3-management
    container_name: rabbitNode2
    hostname: node2.rabbit
    depends_on:
      - rabbitNode1
    networks:
      cluster-network:
        ipv4_address: 192.168.0.11
    extra_hosts:
      - "node1.rabbit:192.168.0.10"
    ports:
      - "4370:4369"
      - "5673:5672"
      - "15673:15672"
      - "25673:25672"
      - "35673:35672"
    environment:
      - RABBITMQ_USE_LONGNAME=true
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_CLUSTERED=true
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@node2.rabbit
      - RABBITMQ_NODENAME=rabbit@node2.rabbit
      - RABBITMQ_CLUSTER_WITH=rabbit@node1.rabbit
      - RABBITMQ_DEFAULT_USER=maxibanex
      - RABBITMQ_DEFAULT_PASS=maxibanexRG20.
    
networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
